# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pythonasap.com
title: Python ASAP
description: >
  Python ASAP is a brilliant set of computer programming education and e-learning services offered by Saman Daneshvar's Coding Academy.
  No matter what level of coding skills you have today, Python ASAP is the best next move for you. Take a free placement test today.

# Enter only the prefix of the email addresses.
contact-email: hello
email-domain: pythonasap.com
# Enter the phone numbers in reverse (for bot protection)
phone: 2178-218 )746(
phone-url: 2178-218-746-1+:let

google-analytics: G-BVS70MVTTB


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Jekyll plugins
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty

# Set the collections directory
collections_dir: all_collections
# Define the collections
collections:
  - courses_to_enroll
  - previous_courses
  - services
  - testimonials


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# social:
#   - title: youtube
#     url: https://www.youtube.com/channel/UCnpJ2mlflHWg3fnQ4aIFLCA
#   - title: linkedin
#     url: https://www.linkedin.com/company/pythonasap
#   - title: github
#     url: https://github.com/pythonasap
#   - title: twitter
#     url: https://twitter.com/pythonasap
#   - title: instagram
#     url: https://www.instagram.com/pythonasap/
#   - title: telegram
#     url: https://t.me/pythonasap
