# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://samandaneshvar.github.io/python2
title: Python ASAP
description: >
  Python ASAP is a brilliant set of computer programming education services offerred by Saman Daneshvar's Coding Academy.
  No matter what level of coding skills you have today, Python ASAP is the best next move for you. Take a free placement test today.
author: Saman Daneshvar
email: info@pythonasap.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Define collections
collections:
  - services
  - testimonials

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: youtube
    url: # https://youtube.com/
  - title: github
    url: # https://github.com/
  - title: linkedin
    url: 
